window.MEDIA_TYPES = {
  official: "OFFICIAL STILL",
  site: "SITE — not the object",
  claimed: "CLAIMED PHOTO — status unresolved or disputed",
  period: "PERIOD ILLUSTRATION — not a photograph of the event",
  poster: "POSTER — category plate, not evidence",
  generated: "GENERATED — not a record"
};
window.MEDIA = {
"emilcin-1978":{type:"site",file:"Emilcin-pomnik.jpg",cap:"Nautilus cube, village monument — not a craft."},
"nazca-lines":{type:"site",file:"Nazca Lines Hummingbird.jpg",cap:"Hummingbird geoglyph from the air."},
"tassili-rockart":{type:"site",file:"Tassili nAjjer.jpg",cap:"Tassili plateau country."},
"roswell-1947":{type:"claimed",file:"Marcel-roswell-debris 0.jpg",cap:"Marcel with Fort Worth debris, 1947. Official line: balloon."},
"derinkuyu":{type:"site",file:"Derinkuyu Underground City.jpg",cap:"Cappadocia underground city."},
"voynich":{type:"official",file:"Voynich Manuscript (129).jpg",cap:"Beinecke folio."},
"tunguska":{type:"site",file:"Tunguska event fallen trees.jpg",cap:"1908 blowdown."},
"nessie":{type:"site",file:"Urquhart Castle and Loch Ness.jpg",cap:"Loch and castle — not a creature."},
"fatima-1917":{type:"site",file:"Sanctuary of Fátima.jpg",cap:"Sanctuary grounds."},
"antikythera":{type:"official",file:"NAMA Machine d'Anticythere 1.jpg",cap:"Mechanism fragments, Athens."},
"lemuria-shasta":{type:"site",file:"Mount Shasta.jpg",cap:"Mount Shasta."},
"wylatowo-circles":{type:"site",file:"Wheat field.jpg",cap:"Grain field stand-in."},
"gdynia-1959":{type:"site",file:"Gdynia harbour.jpg",cap:"Harbour, not a 1959 object."},
"gdansk-bay-uso":{type:"site",file:"Gdańsk Bay.jpg",cap:"Gulf water."},
"baltic-anomaly":{type:"site",file:"Baltic Sea map.jpg",cap:"Basin map. Sonar stills stay with Ocean X."},
"florence-1954":{type:"site",file:"Stadio Artemio Franchi.jpg",cap:"Stadium that stopped play."},
"w56-amicizia":{type:"site",file:"Ascoli Piceno.jpg",cap:"Ascoli country / Rocca Pia vicinity."},
"zanfretta-1978":{type:"site",file:"Apennines Italy.jpg",cap:"Ligurian hinterland type-site."},
"cennina-1954":{type:"site",file:"Tuscany landscape.jpg",cap:"Val d'Ambra country."},
"lascaux":{type:"official",file:"Lascaux painting.jpg",cap:"Documented cave art / replica circuit."},
"chauvet":{type:"site",file:"Pont d'Arc.jpg",cap:"Ardèche approach. Interior restricted."},
"wandjina":{type:"poster",file:"Kimberley Western Australia.jpg",cap:"Country only. Figures not reproduced."},
"nimitz-2004":{type:"official",file:"USS Nimitz (CVN-68).jpg",cap:"Carrier. Tic Tac clips stay on official channels."},
"gimbal-2015":{type:"official",file:"F-A-18 Hornet VFA-103.jpg",cap:"Navy jet context. FLIR on official channels."},
"area-51":{type:"site",file:"Groom Lake.jpg",cap:"Basin / highway country."},
"nautilus-archive":{type:"site",file:"Palace of Culture and Science.jpg",cap:"PKiN, former club rooms."},
"cun-archive":{type:"site",file:"Rome skyline.jpg",cap:"Italian club geography."},
"phoenix-1997":{type:"site",file:"Phoenix Arizona skyline.jpg",cap:"Phoenix basin. Lights were in this sky."},
"rendlesham-1980":{type:"site",file:"Rendlesham Forest.jpg",cap:"Forest east of the old twin bases."},
"walton-1975":{type:"site",file:"Apache-Sitgreaves National Forest.jpg",cap:"Sitgreaves timber country."},
"hill-1961":{type:"site",file:"White Mountains New Hampshire.jpg",cap:"White Mountains corridor."},
"socorro-1964":{type:"site",file:"Socorro New Mexico.jpg",cap:"Socorro high desert."},
"kecksburg-1965":{type:"site",file:"Kecksburg Pennsylvania.jpg",cap:"Village / woods type-site."},
"shag-harbor-1967":{type:"site",file:"Nova Scotia coast.jpg",cap:"South Shore water."},
"pascagoula-1973":{type:"site",file:"Pascagoula River.jpg",cap:"River industrial bank."},
"tehran-1976":{type:"site",file:"Tehran skyline.jpg",cap:"City under the 1976 night."},
"colares-1977":{type:"site",file:"Amazon River Brazil.jpg",cap:"Amazon mouth country."},
"varginha-1996":{type:"site",file:"Varginha.jpg",cap:"Minas Gerais town."},
"voronezh-1989":{type:"site",file:"Voronezh.jpg",cap:"Park city on the Don."},
"ohare-2006":{type:"site",file:"O'Hare International Airport.jpg",cap:"Airport grounds."},
"aguadilla-2013":{type:"site",file:"Aguadilla Puerto Rico.jpg",cap:"Northwest Puerto Rico coast."},
"kenneth-arnold-1947":{type:"site",file:"Mount Rainier.jpg",cap:"Rainier, the 1947 flight line."},
"los-angeles-1942":{type:"period",file:"Battle of Los Angeles 1942.jpg",cap:"Period press / searchlight night."},
"washington-1952":{type:"site",file:"United States Capitol west front.jpg",cap:"Capital under the 1952 flap."},
"nuremberg-1561":{type:"period",file:"Nuremberg 1561 UFO.jpg",cap:"1566 broadsheet of the 1561 sky."},
"basel-1566":{type:"period",file:"Basel 1566 celestial phenomenon.jpg",cap:"Period print."},
"foo-fighters":{type:"period",file:"P-51 Mustang.jpg",cap:"Late-war fighter context, not a foo still."},
"mantell-1948":{type:"site",file:"Kentucky landscape.jpg",cap:"Kentucky air country."},
"levelland-1957":{type:"site",file:"Texas plains.jpg",cap:"South Plains highway country."},
"malmstrom-1967":{type:"site",file:"Montana prairie.jpg",cap:"High-plains missile country."},
"minot-1968":{type:"site",file:"North Dakota prairie.jpg",cap:"Missile-field country."},
"westall-1966":{type:"site",file:"Melbourne suburb.jpg",cap:"South-east Melbourne school country."},
"jal-1628":{type:"site",file:"Alaska Range.jpg",cap:"Alaska night corridor."},
"belgian-wave":{type:"site",file:"Ardennes Belgium.jpg",cap:"Wallonia night country."},
"ariel-1994":{type:"site",file:"Zimbabwe landscape.jpg",cap:"Ruwa school country."},
"skinwalker-1996":{type:"site",file:"Uintah Basin Utah.jpg",cap:"Basin ranch country."},
"omaha-2019":{type:"site",file:"Offutt Air Force Base.jpg",cap:"Offutt / Missouri valley."},
"cash-landrum-1980":{type:"site",file:"East Texas piney woods.jpg",cap:"Piney-woods road."},
"hessdalen":{type:"site",file:"Hessdalen Norway.jpg",cap:"Valley that keeps the lights."},
"trans-en-provence":{type:"site",file:"Provence landscape.jpg",cap:"Var countryside."},
"berwyn-1974":{type:"site",file:"Berwyn Mountains.jpg",cap:"Berwyn ridge."},
"petrozavodsk-1977":{type:"site",file:"Petrozavodsk.jpg",cap:"Karelian capital."},
"dalnegorsk-1986":{type:"site",file:"Sikhote-Alin.jpg",cap:"Far-east ridge country."},
"dyatlov":{type:"site",file:"Ural Mountains.jpg",cap:"Northern Urals."},
"mary-celeste":{type:"period",file:"Mary Celeste 1861.jpg",cap:"Period ship portrait."},
"flannan":{type:"site",file:"Flannan Isles Lighthouse.jpg",cap:"The rock and light."},
"amelia":{type:"official",file:"Amelia Earhart 1937.jpg",cap:"Earhart publicity still."},
"mh370":{type:"official",file:"Malaysia Airlines Boeing 777.jpg",cap:"Type aircraft, not the missing frame."},
"roanoke":{type:"site",file:"Roanoke Island.jpg",cap:"Island shore."},
"wow-signal":{type:"site",file:"Big Ear radio telescope.jpg",cap:"Big Ear dish country."},
"tabbys-star":{type:"official",file:"Kepler Space Telescope.jpg",cap:"Kepler, the photometry machine."},
"baghdad-battery":{type:"official",file:"Baghdad Battery.jpg",cap:"Museum jar."},
"phaistos":{type:"official",file:"Phaistos Disc.jpg",cap:"The disc, Heraklion."},
"bigfoot":{type:"site",file:"Pacific Northwest forest.jpg",cap:"PNW timber. No creature still."},
"yeti":{type:"site",file:"Himalaya.jpg",cap:"High Himalaya."},
"mothman":{type:"site",file:"Point Pleasant West Virginia.jpg",cap:"Ohio River town."},
"jersey-devil":{type:"site",file:"New Jersey Pine Barrens.jpg",cap:"Pine Barrens."},
"chupacabra":{type:"site",file:"Puerto Rico countryside.jpg",cap:"Island interior."},
"champ":{type:"site",file:"Lake Champlain.jpg",cap:"The lake."},
"ogopogo":{type:"site",file:"Okanagan Lake.jpg",cap:"The lake."},
"enfield":{type:"site",file:"Enfield London.jpg",cap:"North London street type-site."},
"amityville":{type:"site",file:"Long Island house.jpg",cap:"Island residential stand-in, not the address."},
"borley":{type:"site",file:"English parish church.jpg",cap:"Essex parish type-site."},
"atlantis-plato":{type:"period",file:"Plato Silanion Musei Capitolini MC1377.jpg",cap:"Plato, not a sunken city."},
"agartha":{type:"period",file:"Hollow earth map.jpg",cap:"Occult map tradition."},
"hollow-earth":{type:"period",file:"Hollow earth map.jpg",cap:"Symmes-style diagram tradition."},
"serpent-mound":{type:"site",file:"Serpent Mound.jpg",cap:"Ohio earthwork from the air."},
"dwarka":{type:"site",file:"Dwarka Gujarat.jpg",cap:"Coastal pilgrimage city."},
"knock-1879":{type:"site",file:"Knock Shrine.jpg",cap:"Shrine basilica."},
"zeitoun-1968":{type:"site",file:"Cairo church.jpg",cap:"Cairo church country."},
"gorgona-1979":{type:"site",file:"Tuscan Archipelago.jpg",cap:"Archipelago water."},
"adriatic-1978":{type:"site",file:"Adriatic Sea.jpg",cap:"Adriatic."},
"torino-caselle-1973":{type:"site",file:"Turin Airport.jpg",cap:"Caselle field."},
"abbiate-guazzone-1950":{type:"site",file:"Varese countryside.jpg",cap:"Varese hinterland."},
"jarnoltowek-2009":{type:"site",file:"Opole Voivodeship.jpg",cap:"Opole upland."},
"nadarzyce-1994":{type:"site",file:"Drawsko Lake District.jpg",cap:"Drawsko lake country."},
"muszyna-1958":{type:"site",file:"Beskid Mountains.jpg",cap:"Sądecki Beskid."},
"targowek-1922":{type:"site",file:"Warsaw Targówek.jpg",cap:"North-east Warsaw."},
"lazar-1989":{type:"site",file:"Papoose Lake.jpg",cap:"Range country associated with the S-4 story."},
"blue-book":{type:"official",file:"Wright-Patterson Air Force Base.jpg",cap:"Wright-Patt, paper home of the project."},
"aatip":{type:"official",file:"The Pentagon US Department of Defense building.jpg",cap:"Building, not a craft."},
"grusch-2023":{type:"official",file:"United States Capitol.jpg",cap:"Hearing house."},
"jfk":{type:"official",file:"John F. Kennedy Official Portrait.jpg",cap:"Official portrait. File is the paper trail, not a new still."},
"mkultra":{type:"official",file:"CIA headquarters.jpg",cap:"Langley campus."},
"nuremberg-1561":{type:"period",file:"Celestial phenomenon over Nuremberg 1561.jpg",cap:"1561 broadsheet."}
};
